server: true
page_title: "Yar's Voting Guide"
title: "Yar's Voting Guide"
tagline: Oakland, California, November 2018
repository_url: https://github.com/yardenac/yar-votes.github.io/
permalink: pretty
markdown: kramdown
